//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KVM.wrPeoples {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PeoplesSoap", Namespace="http://tempuri.org/")]
    public partial class Peoples : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _GetCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback _UpdateCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback _DeleteCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetCustomerAccountByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetCustomerAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetCustomerBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddCustomerTransOperationCompleted;
        
        private System.Threading.SendOrPostCallback DefaultCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback _CustomerDetailReportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _CustomerDetailReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AccountStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSuppliersOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback _UpdateSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback _DeleteSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSupplierAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSupplierBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddSupplierTransOperationCompleted;
        
        private System.Threading.SendOrPostCallback _DefaultSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback _SupplierDetailReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Peoples() {
            this.Url = global::KVM.Properties.Settings.Default.KV_Mart_wrPeoples_Peoples;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _GetCustomerCompletedEventHandler _GetCustomerCompleted;
        
        /// <remarks/>
        public event _GetCustomersCompletedEventHandler _GetCustomersCompleted;
        
        /// <remarks/>
        public event _AddCustomerCompletedEventHandler _AddCustomerCompleted;
        
        /// <remarks/>
        public event _UpdateCustomerCompletedEventHandler _UpdateCustomerCompleted;
        
        /// <remarks/>
        public event _DeleteCustomerCompletedEventHandler _DeleteCustomerCompleted;
        
        /// <remarks/>
        public event _GetCustomerAccountByIDCompletedEventHandler _GetCustomerAccountByIDCompleted;
        
        /// <remarks/>
        public event _GetCustomerAccountCompletedEventHandler _GetCustomerAccountCompleted;
        
        /// <remarks/>
        public event _GetCustomerBalanceCompletedEventHandler _GetCustomerBalanceCompleted;
        
        /// <remarks/>
        public event _AddCustomerTransCompletedEventHandler _AddCustomerTransCompleted;
        
        /// <remarks/>
        public event DefaultCustomerCompletedEventHandler DefaultCustomerCompleted;
        
        /// <remarks/>
        public event _CustomerDetailReportsCompletedEventHandler _CustomerDetailReportsCompleted;
        
        /// <remarks/>
        public event _CustomerDetailReportCompletedEventHandler _CustomerDetailReportCompleted;
        
        /// <remarks/>
        public event _AccountStatementCompletedEventHandler _AccountStatementCompleted;
        
        /// <remarks/>
        public event _GetSuppliersCompletedEventHandler _GetSuppliersCompleted;
        
        /// <remarks/>
        public event _GetSupplierCompletedEventHandler _GetSupplierCompleted;
        
        /// <remarks/>
        public event _AddSupplierCompletedEventHandler _AddSupplierCompleted;
        
        /// <remarks/>
        public event _UpdateSupplierCompletedEventHandler _UpdateSupplierCompleted;
        
        /// <remarks/>
        public event _DeleteSupplierCompletedEventHandler _DeleteSupplierCompleted;
        
        /// <remarks/>
        public event _GetSupplierAccountCompletedEventHandler _GetSupplierAccountCompleted;
        
        /// <remarks/>
        public event _GetSupplierBalanceCompletedEventHandler _GetSupplierBalanceCompleted;
        
        /// <remarks/>
        public event _AddSupplierTransCompletedEventHandler _AddSupplierTransCompleted;
        
        /// <remarks/>
        public event _DefaultSupplierCompletedEventHandler _DefaultSupplierCompleted;
        
        /// <remarks/>
        public event _SupplierDetailReportCompletedEventHandler _SupplierDetailReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer _GetCustomer(int CustomerID) {
            object[] results = this.Invoke("_GetCustomer", new object[] {
                        CustomerID});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCustomerAsync(int CustomerID) {
            this._GetCustomerAsync(CustomerID, null);
        }
        
        /// <remarks/>
        public void _GetCustomerAsync(int CustomerID, object userState) {
            if ((this._GetCustomerOperationCompleted == null)) {
                this._GetCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCustomerOperationCompleted);
            }
            this.InvokeAsync("_GetCustomer", new object[] {
                        CustomerID}, this._GetCustomerOperationCompleted, userState);
        }
        
        private void On_GetCustomerOperationCompleted(object arg) {
            if ((this._GetCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCustomerCompleted(this, new _GetCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetCustomers() {
            object[] results = this.Invoke("_GetCustomers", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCustomersAsync() {
            this._GetCustomersAsync(null);
        }
        
        /// <remarks/>
        public void _GetCustomersAsync(object userState) {
            if ((this._GetCustomersOperationCompleted == null)) {
                this._GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCustomersOperationCompleted);
            }
            this.InvokeAsync("_GetCustomers", new object[0], this._GetCustomersOperationCompleted, userState);
        }
        
        private void On_GetCustomersOperationCompleted(object arg) {
            if ((this._GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCustomersCompleted(this, new _GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddCustomer(Customer c) {
            object[] results = this.Invoke("_AddCustomer", new object[] {
                        c});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddCustomerAsync(Customer c) {
            this._AddCustomerAsync(c, null);
        }
        
        /// <remarks/>
        public void _AddCustomerAsync(Customer c, object userState) {
            if ((this._AddCustomerOperationCompleted == null)) {
                this._AddCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddCustomerOperationCompleted);
            }
            this.InvokeAsync("_AddCustomer", new object[] {
                        c}, this._AddCustomerOperationCompleted, userState);
        }
        
        private void On_AddCustomerOperationCompleted(object arg) {
            if ((this._AddCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddCustomerCompleted(this, new _AddCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_UpdateCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _UpdateCustomer(Customer c) {
            object[] results = this.Invoke("_UpdateCustomer", new object[] {
                        c});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _UpdateCustomerAsync(Customer c) {
            this._UpdateCustomerAsync(c, null);
        }
        
        /// <remarks/>
        public void _UpdateCustomerAsync(Customer c, object userState) {
            if ((this._UpdateCustomerOperationCompleted == null)) {
                this._UpdateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.On_UpdateCustomerOperationCompleted);
            }
            this.InvokeAsync("_UpdateCustomer", new object[] {
                        c}, this._UpdateCustomerOperationCompleted, userState);
        }
        
        private void On_UpdateCustomerOperationCompleted(object arg) {
            if ((this._UpdateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._UpdateCustomerCompleted(this, new _UpdateCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_DeleteCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _DeleteCustomer(int ID) {
            object[] results = this.Invoke("_DeleteCustomer", new object[] {
                        ID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _DeleteCustomerAsync(int ID) {
            this._DeleteCustomerAsync(ID, null);
        }
        
        /// <remarks/>
        public void _DeleteCustomerAsync(int ID, object userState) {
            if ((this._DeleteCustomerOperationCompleted == null)) {
                this._DeleteCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.On_DeleteCustomerOperationCompleted);
            }
            this.InvokeAsync("_DeleteCustomer", new object[] {
                        ID}, this._DeleteCustomerOperationCompleted, userState);
        }
        
        private void On_DeleteCustomerOperationCompleted(object arg) {
            if ((this._DeleteCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._DeleteCustomerCompleted(this, new _DeleteCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCustomerAccountByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetCustomerAccountByID(int CustomerID) {
            object[] results = this.Invoke("_GetCustomerAccountByID", new object[] {
                        CustomerID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCustomerAccountByIDAsync(int CustomerID) {
            this._GetCustomerAccountByIDAsync(CustomerID, null);
        }
        
        /// <remarks/>
        public void _GetCustomerAccountByIDAsync(int CustomerID, object userState) {
            if ((this._GetCustomerAccountByIDOperationCompleted == null)) {
                this._GetCustomerAccountByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCustomerAccountByIDOperationCompleted);
            }
            this.InvokeAsync("_GetCustomerAccountByID", new object[] {
                        CustomerID}, this._GetCustomerAccountByIDOperationCompleted, userState);
        }
        
        private void On_GetCustomerAccountByIDOperationCompleted(object arg) {
            if ((this._GetCustomerAccountByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCustomerAccountByIDCompleted(this, new _GetCustomerAccountByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCustomerAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetCustomerAccount() {
            object[] results = this.Invoke("_GetCustomerAccount", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCustomerAccountAsync() {
            this._GetCustomerAccountAsync(null);
        }
        
        /// <remarks/>
        public void _GetCustomerAccountAsync(object userState) {
            if ((this._GetCustomerAccountOperationCompleted == null)) {
                this._GetCustomerAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCustomerAccountOperationCompleted);
            }
            this.InvokeAsync("_GetCustomerAccount", new object[0], this._GetCustomerAccountOperationCompleted, userState);
        }
        
        private void On_GetCustomerAccountOperationCompleted(object arg) {
            if ((this._GetCustomerAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCustomerAccountCompleted(this, new _GetCustomerAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCustomerBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetCustomerBalance(int CustomerID) {
            object[] results = this.Invoke("_GetCustomerBalance", new object[] {
                        CustomerID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCustomerBalanceAsync(int CustomerID) {
            this._GetCustomerBalanceAsync(CustomerID, null);
        }
        
        /// <remarks/>
        public void _GetCustomerBalanceAsync(int CustomerID, object userState) {
            if ((this._GetCustomerBalanceOperationCompleted == null)) {
                this._GetCustomerBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCustomerBalanceOperationCompleted);
            }
            this.InvokeAsync("_GetCustomerBalance", new object[] {
                        CustomerID}, this._GetCustomerBalanceOperationCompleted, userState);
        }
        
        private void On_GetCustomerBalanceOperationCompleted(object arg) {
            if ((this._GetCustomerBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCustomerBalanceCompleted(this, new _GetCustomerBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddCustomerTrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddCustomerTrans(CustomerAccount ca) {
            object[] results = this.Invoke("_AddCustomerTrans", new object[] {
                        ca});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddCustomerTransAsync(CustomerAccount ca) {
            this._AddCustomerTransAsync(ca, null);
        }
        
        /// <remarks/>
        public void _AddCustomerTransAsync(CustomerAccount ca, object userState) {
            if ((this._AddCustomerTransOperationCompleted == null)) {
                this._AddCustomerTransOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddCustomerTransOperationCompleted);
            }
            this.InvokeAsync("_AddCustomerTrans", new object[] {
                        ca}, this._AddCustomerTransOperationCompleted, userState);
        }
        
        private void On_AddCustomerTransOperationCompleted(object arg) {
            if ((this._AddCustomerTransCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddCustomerTransCompleted(this, new _AddCustomerTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DefaultCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer DefaultCustomer() {
            object[] results = this.Invoke("DefaultCustomer", new object[0]);
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void DefaultCustomerAsync() {
            this.DefaultCustomerAsync(null);
        }
        
        /// <remarks/>
        public void DefaultCustomerAsync(object userState) {
            if ((this.DefaultCustomerOperationCompleted == null)) {
                this.DefaultCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDefaultCustomerOperationCompleted);
            }
            this.InvokeAsync("DefaultCustomer", new object[0], this.DefaultCustomerOperationCompleted, userState);
        }
        
        private void OnDefaultCustomerOperationCompleted(object arg) {
            if ((this.DefaultCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DefaultCustomerCompleted(this, new DefaultCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_CustomerDetailReports", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _CustomerDetailReports() {
            object[] results = this.Invoke("_CustomerDetailReports", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _CustomerDetailReportsAsync() {
            this._CustomerDetailReportsAsync(null);
        }
        
        /// <remarks/>
        public void _CustomerDetailReportsAsync(object userState) {
            if ((this._CustomerDetailReportsOperationCompleted == null)) {
                this._CustomerDetailReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_CustomerDetailReportsOperationCompleted);
            }
            this.InvokeAsync("_CustomerDetailReports", new object[0], this._CustomerDetailReportsOperationCompleted, userState);
        }
        
        private void On_CustomerDetailReportsOperationCompleted(object arg) {
            if ((this._CustomerDetailReportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._CustomerDetailReportsCompleted(this, new _CustomerDetailReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_CustomerDetailReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _CustomerDetailReport(int CustomerID) {
            object[] results = this.Invoke("_CustomerDetailReport", new object[] {
                        CustomerID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _CustomerDetailReportAsync(int CustomerID) {
            this._CustomerDetailReportAsync(CustomerID, null);
        }
        
        /// <remarks/>
        public void _CustomerDetailReportAsync(int CustomerID, object userState) {
            if ((this._CustomerDetailReportOperationCompleted == null)) {
                this._CustomerDetailReportOperationCompleted = new System.Threading.SendOrPostCallback(this.On_CustomerDetailReportOperationCompleted);
            }
            this.InvokeAsync("_CustomerDetailReport", new object[] {
                        CustomerID}, this._CustomerDetailReportOperationCompleted, userState);
        }
        
        private void On_CustomerDetailReportOperationCompleted(object arg) {
            if ((this._CustomerDetailReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._CustomerDetailReportCompleted(this, new _CustomerDetailReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AccountStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AccountStatement(int CustomerID, System.DateTime DateFrom, System.DateTime DateTo) {
            object[] results = this.Invoke("_AccountStatement", new object[] {
                        CustomerID,
                        DateFrom,
                        DateTo});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AccountStatementAsync(int CustomerID, System.DateTime DateFrom, System.DateTime DateTo) {
            this._AccountStatementAsync(CustomerID, DateFrom, DateTo, null);
        }
        
        /// <remarks/>
        public void _AccountStatementAsync(int CustomerID, System.DateTime DateFrom, System.DateTime DateTo, object userState) {
            if ((this._AccountStatementOperationCompleted == null)) {
                this._AccountStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AccountStatementOperationCompleted);
            }
            this.InvokeAsync("_AccountStatement", new object[] {
                        CustomerID,
                        DateFrom,
                        DateTo}, this._AccountStatementOperationCompleted, userState);
        }
        
        private void On_AccountStatementOperationCompleted(object arg) {
            if ((this._AccountStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AccountStatementCompleted(this, new _AccountStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSuppliers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSuppliers() {
            object[] results = this.Invoke("_GetSuppliers", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSuppliersAsync() {
            this._GetSuppliersAsync(null);
        }
        
        /// <remarks/>
        public void _GetSuppliersAsync(object userState) {
            if ((this._GetSuppliersOperationCompleted == null)) {
                this._GetSuppliersOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSuppliersOperationCompleted);
            }
            this.InvokeAsync("_GetSuppliers", new object[0], this._GetSuppliersOperationCompleted, userState);
        }
        
        private void On_GetSuppliersOperationCompleted(object arg) {
            if ((this._GetSuppliersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSuppliersCompleted(this, new _GetSuppliersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSupplier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Supplier _GetSupplier(int ID) {
            object[] results = this.Invoke("_GetSupplier", new object[] {
                        ID});
            return ((Supplier)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSupplierAsync(int ID) {
            this._GetSupplierAsync(ID, null);
        }
        
        /// <remarks/>
        public void _GetSupplierAsync(int ID, object userState) {
            if ((this._GetSupplierOperationCompleted == null)) {
                this._GetSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSupplierOperationCompleted);
            }
            this.InvokeAsync("_GetSupplier", new object[] {
                        ID}, this._GetSupplierOperationCompleted, userState);
        }
        
        private void On_GetSupplierOperationCompleted(object arg) {
            if ((this._GetSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSupplierCompleted(this, new _GetSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddSupplier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddSupplier(Supplier s) {
            object[] results = this.Invoke("_AddSupplier", new object[] {
                        s});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddSupplierAsync(Supplier s) {
            this._AddSupplierAsync(s, null);
        }
        
        /// <remarks/>
        public void _AddSupplierAsync(Supplier s, object userState) {
            if ((this._AddSupplierOperationCompleted == null)) {
                this._AddSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddSupplierOperationCompleted);
            }
            this.InvokeAsync("_AddSupplier", new object[] {
                        s}, this._AddSupplierOperationCompleted, userState);
        }
        
        private void On_AddSupplierOperationCompleted(object arg) {
            if ((this._AddSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddSupplierCompleted(this, new _AddSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_UpdateSupplier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _UpdateSupplier(Supplier s) {
            object[] results = this.Invoke("_UpdateSupplier", new object[] {
                        s});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _UpdateSupplierAsync(Supplier s) {
            this._UpdateSupplierAsync(s, null);
        }
        
        /// <remarks/>
        public void _UpdateSupplierAsync(Supplier s, object userState) {
            if ((this._UpdateSupplierOperationCompleted == null)) {
                this._UpdateSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.On_UpdateSupplierOperationCompleted);
            }
            this.InvokeAsync("_UpdateSupplier", new object[] {
                        s}, this._UpdateSupplierOperationCompleted, userState);
        }
        
        private void On_UpdateSupplierOperationCompleted(object arg) {
            if ((this._UpdateSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._UpdateSupplierCompleted(this, new _UpdateSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_DeleteSupplier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _DeleteSupplier(int ID) {
            object[] results = this.Invoke("_DeleteSupplier", new object[] {
                        ID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _DeleteSupplierAsync(int ID) {
            this._DeleteSupplierAsync(ID, null);
        }
        
        /// <remarks/>
        public void _DeleteSupplierAsync(int ID, object userState) {
            if ((this._DeleteSupplierOperationCompleted == null)) {
                this._DeleteSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.On_DeleteSupplierOperationCompleted);
            }
            this.InvokeAsync("_DeleteSupplier", new object[] {
                        ID}, this._DeleteSupplierOperationCompleted, userState);
        }
        
        private void On_DeleteSupplierOperationCompleted(object arg) {
            if ((this._DeleteSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._DeleteSupplierCompleted(this, new _DeleteSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSupplierAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSupplierAccount() {
            object[] results = this.Invoke("_GetSupplierAccount", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSupplierAccountAsync() {
            this._GetSupplierAccountAsync(null);
        }
        
        /// <remarks/>
        public void _GetSupplierAccountAsync(object userState) {
            if ((this._GetSupplierAccountOperationCompleted == null)) {
                this._GetSupplierAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSupplierAccountOperationCompleted);
            }
            this.InvokeAsync("_GetSupplierAccount", new object[0], this._GetSupplierAccountOperationCompleted, userState);
        }
        
        private void On_GetSupplierAccountOperationCompleted(object arg) {
            if ((this._GetSupplierAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSupplierAccountCompleted(this, new _GetSupplierAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSupplierBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSupplierBalance(int ID) {
            object[] results = this.Invoke("_GetSupplierBalance", new object[] {
                        ID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSupplierBalanceAsync(int ID) {
            this._GetSupplierBalanceAsync(ID, null);
        }
        
        /// <remarks/>
        public void _GetSupplierBalanceAsync(int ID, object userState) {
            if ((this._GetSupplierBalanceOperationCompleted == null)) {
                this._GetSupplierBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSupplierBalanceOperationCompleted);
            }
            this.InvokeAsync("_GetSupplierBalance", new object[] {
                        ID}, this._GetSupplierBalanceOperationCompleted, userState);
        }
        
        private void On_GetSupplierBalanceOperationCompleted(object arg) {
            if ((this._GetSupplierBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSupplierBalanceCompleted(this, new _GetSupplierBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddSupplierTrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddSupplierTrans(SupplierAccount sa) {
            object[] results = this.Invoke("_AddSupplierTrans", new object[] {
                        sa});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddSupplierTransAsync(SupplierAccount sa) {
            this._AddSupplierTransAsync(sa, null);
        }
        
        /// <remarks/>
        public void _AddSupplierTransAsync(SupplierAccount sa, object userState) {
            if ((this._AddSupplierTransOperationCompleted == null)) {
                this._AddSupplierTransOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddSupplierTransOperationCompleted);
            }
            this.InvokeAsync("_AddSupplierTrans", new object[] {
                        sa}, this._AddSupplierTransOperationCompleted, userState);
        }
        
        private void On_AddSupplierTransOperationCompleted(object arg) {
            if ((this._AddSupplierTransCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddSupplierTransCompleted(this, new _AddSupplierTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_DefaultSupplier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Supplier _DefaultSupplier() {
            object[] results = this.Invoke("_DefaultSupplier", new object[0]);
            return ((Supplier)(results[0]));
        }
        
        /// <remarks/>
        public void _DefaultSupplierAsync() {
            this._DefaultSupplierAsync(null);
        }
        
        /// <remarks/>
        public void _DefaultSupplierAsync(object userState) {
            if ((this._DefaultSupplierOperationCompleted == null)) {
                this._DefaultSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.On_DefaultSupplierOperationCompleted);
            }
            this.InvokeAsync("_DefaultSupplier", new object[0], this._DefaultSupplierOperationCompleted, userState);
        }
        
        private void On_DefaultSupplierOperationCompleted(object arg) {
            if ((this._DefaultSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._DefaultSupplierCompleted(this, new _DefaultSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_SupplierDetailReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _SupplierDetailReport() {
            object[] results = this.Invoke("_SupplierDetailReport", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _SupplierDetailReportAsync() {
            this._SupplierDetailReportAsync(null);
        }
        
        /// <remarks/>
        public void _SupplierDetailReportAsync(object userState) {
            if ((this._SupplierDetailReportOperationCompleted == null)) {
                this._SupplierDetailReportOperationCompleted = new System.Threading.SendOrPostCallback(this.On_SupplierDetailReportOperationCompleted);
            }
            this.InvokeAsync("_SupplierDetailReport", new object[0], this._SupplierDetailReportOperationCompleted, userState);
        }
        
        private void On_SupplierDetailReportOperationCompleted(object arg) {
            if ((this._SupplierDetailReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._SupplierDetailReportCompleted(this, new _SupplierDetailReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private int idField;
        
        private string customerNameField;
        
        private string addressField;
        
        private string phoneField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SupplierAccount {
        
        private int idField;
        
        private int supplierIDField;
        
        private System.DateTime transDateField;
        
        private string descriptionField;
        
        private double debitField;
        
        private double creditField;
        
        private double balanceField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Debit {
            get {
                return this.debitField;
            }
            set {
                this.debitField = value;
            }
        }
        
        /// <remarks/>
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Supplier {
        
        private int idField;
        
        private string supplierNameField;
        
        private string addressField;
        
        private string phoneField;
        
        private string cSTField;
        
        private string tINField;
        
        private string gSTINField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string CST {
            get {
                return this.cSTField;
            }
            set {
                this.cSTField = value;
            }
        }
        
        /// <remarks/>
        public string TIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
            }
        }
        
        /// <remarks/>
        public string GSTIN {
            get {
                return this.gSTINField;
            }
            set {
                this.gSTINField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerAccount {
        
        private int idField;
        
        private int customerIDField;
        
        private System.DateTime transDateField;
        
        private string descriptionField;
        
        private double debitField;
        
        private double creditField;
        
        private double balanceField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Debit {
            get {
                return this.debitField;
            }
            set {
                this.debitField = value;
            }
        }
        
        /// <remarks/>
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServerToClient {
        
        private int countField;
        
        private double valueField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        private string messageField;
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DS {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCustomerCompletedEventHandler(object sender, _GetCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCustomersCompletedEventHandler(object sender, _GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddCustomerCompletedEventHandler(object sender, _AddCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _UpdateCustomerCompletedEventHandler(object sender, _UpdateCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _UpdateCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _UpdateCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _DeleteCustomerCompletedEventHandler(object sender, _DeleteCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _DeleteCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _DeleteCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCustomerAccountByIDCompletedEventHandler(object sender, _GetCustomerAccountByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCustomerAccountByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCustomerAccountByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCustomerAccountCompletedEventHandler(object sender, _GetCustomerAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCustomerAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCustomerAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCustomerBalanceCompletedEventHandler(object sender, _GetCustomerBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCustomerBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCustomerBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddCustomerTransCompletedEventHandler(object sender, _AddCustomerTransCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddCustomerTransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddCustomerTransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DefaultCustomerCompletedEventHandler(object sender, DefaultCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DefaultCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DefaultCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _CustomerDetailReportsCompletedEventHandler(object sender, _CustomerDetailReportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _CustomerDetailReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _CustomerDetailReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _CustomerDetailReportCompletedEventHandler(object sender, _CustomerDetailReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _CustomerDetailReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _CustomerDetailReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AccountStatementCompletedEventHandler(object sender, _AccountStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AccountStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AccountStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSuppliersCompletedEventHandler(object sender, _GetSuppliersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSuppliersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSuppliersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSupplierCompletedEventHandler(object sender, _GetSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Supplier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Supplier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddSupplierCompletedEventHandler(object sender, _AddSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _UpdateSupplierCompletedEventHandler(object sender, _UpdateSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _UpdateSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _UpdateSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _DeleteSupplierCompletedEventHandler(object sender, _DeleteSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _DeleteSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _DeleteSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSupplierAccountCompletedEventHandler(object sender, _GetSupplierAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSupplierAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSupplierAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSupplierBalanceCompletedEventHandler(object sender, _GetSupplierBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSupplierBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSupplierBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddSupplierTransCompletedEventHandler(object sender, _AddSupplierTransCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddSupplierTransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddSupplierTransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _DefaultSupplierCompletedEventHandler(object sender, _DefaultSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _DefaultSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _DefaultSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Supplier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Supplier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _SupplierDetailReportCompletedEventHandler(object sender, _SupplierDetailReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _SupplierDetailReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _SupplierDetailReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591