//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KVM.wrTransact {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransactSoap", Namespace="http://tempuri.org/")]
    public partial class Transact : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _AddPurchaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddPurchaseDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback _ViewPurchaseByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback _ViewPurchaseByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddSaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddSaleDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSalesByInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSalesByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSalesByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _QuickSaleReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback _SalesByProductNameChartOperationCompleted;
        
        private System.Threading.SendOrPostCallback _SalesByProductQuantityChartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Transact() {
            this.Url = global::KVM.Properties.Settings.Default.KV_Mart_wrTransact_Transact;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _AddPurchaseCompletedEventHandler _AddPurchaseCompleted;
        
        /// <remarks/>
        public event _AddPurchaseDetailCompletedEventHandler _AddPurchaseDetailCompleted;
        
        /// <remarks/>
        public event _ViewPurchaseByDateCompletedEventHandler _ViewPurchaseByDateCompleted;
        
        /// <remarks/>
        public event _ViewPurchaseByDatesCompletedEventHandler _ViewPurchaseByDatesCompleted;
        
        /// <remarks/>
        public event _AddSaleCompletedEventHandler _AddSaleCompleted;
        
        /// <remarks/>
        public event _AddSaleDetailsCompletedEventHandler _AddSaleDetailsCompleted;
        
        /// <remarks/>
        public event _GetSalesCompletedEventHandler _GetSalesCompleted;
        
        /// <remarks/>
        public event _GetSalesByInvoiceCompletedEventHandler _GetSalesByInvoiceCompleted;
        
        /// <remarks/>
        public event _GetSalesByDateCompletedEventHandler _GetSalesByDateCompleted;
        
        /// <remarks/>
        public event _GetSalesByDatesCompletedEventHandler _GetSalesByDatesCompleted;
        
        /// <remarks/>
        public event _QuickSaleReportCompletedEventHandler _QuickSaleReportCompleted;
        
        /// <remarks/>
        public event _SalesByProductNameChartCompletedEventHandler _SalesByProductNameChartCompleted;
        
        /// <remarks/>
        public event _SalesByProductQuantityChartCompletedEventHandler _SalesByProductQuantityChartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddPurchase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddPurchase(Purchase p) {
            object[] results = this.Invoke("_AddPurchase", new object[] {
                        p});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddPurchaseAsync(Purchase p) {
            this._AddPurchaseAsync(p, null);
        }
        
        /// <remarks/>
        public void _AddPurchaseAsync(Purchase p, object userState) {
            if ((this._AddPurchaseOperationCompleted == null)) {
                this._AddPurchaseOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddPurchaseOperationCompleted);
            }
            this.InvokeAsync("_AddPurchase", new object[] {
                        p}, this._AddPurchaseOperationCompleted, userState);
        }
        
        private void On_AddPurchaseOperationCompleted(object arg) {
            if ((this._AddPurchaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddPurchaseCompleted(this, new _AddPurchaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddPurchaseDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddPurchaseDetail(PurchaseDetail pd) {
            object[] results = this.Invoke("_AddPurchaseDetail", new object[] {
                        pd});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddPurchaseDetailAsync(PurchaseDetail pd) {
            this._AddPurchaseDetailAsync(pd, null);
        }
        
        /// <remarks/>
        public void _AddPurchaseDetailAsync(PurchaseDetail pd, object userState) {
            if ((this._AddPurchaseDetailOperationCompleted == null)) {
                this._AddPurchaseDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddPurchaseDetailOperationCompleted);
            }
            this.InvokeAsync("_AddPurchaseDetail", new object[] {
                        pd}, this._AddPurchaseDetailOperationCompleted, userState);
        }
        
        private void On_AddPurchaseDetailOperationCompleted(object arg) {
            if ((this._AddPurchaseDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddPurchaseDetailCompleted(this, new _AddPurchaseDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_ViewPurchaseByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _ViewPurchaseByDate(System.DateTime date) {
            object[] results = this.Invoke("_ViewPurchaseByDate", new object[] {
                        date});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _ViewPurchaseByDateAsync(System.DateTime date) {
            this._ViewPurchaseByDateAsync(date, null);
        }
        
        /// <remarks/>
        public void _ViewPurchaseByDateAsync(System.DateTime date, object userState) {
            if ((this._ViewPurchaseByDateOperationCompleted == null)) {
                this._ViewPurchaseByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.On_ViewPurchaseByDateOperationCompleted);
            }
            this.InvokeAsync("_ViewPurchaseByDate", new object[] {
                        date}, this._ViewPurchaseByDateOperationCompleted, userState);
        }
        
        private void On_ViewPurchaseByDateOperationCompleted(object arg) {
            if ((this._ViewPurchaseByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._ViewPurchaseByDateCompleted(this, new _ViewPurchaseByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_ViewPurchaseByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _ViewPurchaseByDates(System.DateTime date1, System.DateTime date2) {
            object[] results = this.Invoke("_ViewPurchaseByDates", new object[] {
                        date1,
                        date2});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _ViewPurchaseByDatesAsync(System.DateTime date1, System.DateTime date2) {
            this._ViewPurchaseByDatesAsync(date1, date2, null);
        }
        
        /// <remarks/>
        public void _ViewPurchaseByDatesAsync(System.DateTime date1, System.DateTime date2, object userState) {
            if ((this._ViewPurchaseByDatesOperationCompleted == null)) {
                this._ViewPurchaseByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_ViewPurchaseByDatesOperationCompleted);
            }
            this.InvokeAsync("_ViewPurchaseByDates", new object[] {
                        date1,
                        date2}, this._ViewPurchaseByDatesOperationCompleted, userState);
        }
        
        private void On_ViewPurchaseByDatesOperationCompleted(object arg) {
            if ((this._ViewPurchaseByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._ViewPurchaseByDatesCompleted(this, new _ViewPurchaseByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddSale", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddSale(Sale s) {
            object[] results = this.Invoke("_AddSale", new object[] {
                        s});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddSaleAsync(Sale s) {
            this._AddSaleAsync(s, null);
        }
        
        /// <remarks/>
        public void _AddSaleAsync(Sale s, object userState) {
            if ((this._AddSaleOperationCompleted == null)) {
                this._AddSaleOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddSaleOperationCompleted);
            }
            this.InvokeAsync("_AddSale", new object[] {
                        s}, this._AddSaleOperationCompleted, userState);
        }
        
        private void On_AddSaleOperationCompleted(object arg) {
            if ((this._AddSaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddSaleCompleted(this, new _AddSaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddSaleDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddSaleDetails(SaleDetail sd) {
            object[] results = this.Invoke("_AddSaleDetails", new object[] {
                        sd});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddSaleDetailsAsync(SaleDetail sd) {
            this._AddSaleDetailsAsync(sd, null);
        }
        
        /// <remarks/>
        public void _AddSaleDetailsAsync(SaleDetail sd, object userState) {
            if ((this._AddSaleDetailsOperationCompleted == null)) {
                this._AddSaleDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddSaleDetailsOperationCompleted);
            }
            this.InvokeAsync("_AddSaleDetails", new object[] {
                        sd}, this._AddSaleDetailsOperationCompleted, userState);
        }
        
        private void On_AddSaleDetailsOperationCompleted(object arg) {
            if ((this._AddSaleDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddSaleDetailsCompleted(this, new _AddSaleDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSales() {
            object[] results = this.Invoke("_GetSales", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSalesAsync() {
            this._GetSalesAsync(null);
        }
        
        /// <remarks/>
        public void _GetSalesAsync(object userState) {
            if ((this._GetSalesOperationCompleted == null)) {
                this._GetSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSalesOperationCompleted);
            }
            this.InvokeAsync("_GetSales", new object[0], this._GetSalesOperationCompleted, userState);
        }
        
        private void On_GetSalesOperationCompleted(object arg) {
            if ((this._GetSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSalesCompleted(this, new _GetSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSalesByInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSalesByInvoice(string InvoiceNo) {
            object[] results = this.Invoke("_GetSalesByInvoice", new object[] {
                        InvoiceNo});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSalesByInvoiceAsync(string InvoiceNo) {
            this._GetSalesByInvoiceAsync(InvoiceNo, null);
        }
        
        /// <remarks/>
        public void _GetSalesByInvoiceAsync(string InvoiceNo, object userState) {
            if ((this._GetSalesByInvoiceOperationCompleted == null)) {
                this._GetSalesByInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSalesByInvoiceOperationCompleted);
            }
            this.InvokeAsync("_GetSalesByInvoice", new object[] {
                        InvoiceNo}, this._GetSalesByInvoiceOperationCompleted, userState);
        }
        
        private void On_GetSalesByInvoiceOperationCompleted(object arg) {
            if ((this._GetSalesByInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSalesByInvoiceCompleted(this, new _GetSalesByInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSalesByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSalesByDate(System.DateTime sellDate) {
            object[] results = this.Invoke("_GetSalesByDate", new object[] {
                        sellDate});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSalesByDateAsync(System.DateTime sellDate) {
            this._GetSalesByDateAsync(sellDate, null);
        }
        
        /// <remarks/>
        public void _GetSalesByDateAsync(System.DateTime sellDate, object userState) {
            if ((this._GetSalesByDateOperationCompleted == null)) {
                this._GetSalesByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSalesByDateOperationCompleted);
            }
            this.InvokeAsync("_GetSalesByDate", new object[] {
                        sellDate}, this._GetSalesByDateOperationCompleted, userState);
        }
        
        private void On_GetSalesByDateOperationCompleted(object arg) {
            if ((this._GetSalesByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSalesByDateCompleted(this, new _GetSalesByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSalesByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSalesByDates(System.DateTime date1, System.DateTime date2) {
            object[] results = this.Invoke("_GetSalesByDates", new object[] {
                        date1,
                        date2});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSalesByDatesAsync(System.DateTime date1, System.DateTime date2) {
            this._GetSalesByDatesAsync(date1, date2, null);
        }
        
        /// <remarks/>
        public void _GetSalesByDatesAsync(System.DateTime date1, System.DateTime date2, object userState) {
            if ((this._GetSalesByDatesOperationCompleted == null)) {
                this._GetSalesByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSalesByDatesOperationCompleted);
            }
            this.InvokeAsync("_GetSalesByDates", new object[] {
                        date1,
                        date2}, this._GetSalesByDatesOperationCompleted, userState);
        }
        
        private void On_GetSalesByDatesOperationCompleted(object arg) {
            if ((this._GetSalesByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSalesByDatesCompleted(this, new _GetSalesByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_QuickSaleReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _QuickSaleReport(string InvoiceNo) {
            object[] results = this.Invoke("_QuickSaleReport", new object[] {
                        InvoiceNo});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _QuickSaleReportAsync(string InvoiceNo) {
            this._QuickSaleReportAsync(InvoiceNo, null);
        }
        
        /// <remarks/>
        public void _QuickSaleReportAsync(string InvoiceNo, object userState) {
            if ((this._QuickSaleReportOperationCompleted == null)) {
                this._QuickSaleReportOperationCompleted = new System.Threading.SendOrPostCallback(this.On_QuickSaleReportOperationCompleted);
            }
            this.InvokeAsync("_QuickSaleReport", new object[] {
                        InvoiceNo}, this._QuickSaleReportOperationCompleted, userState);
        }
        
        private void On_QuickSaleReportOperationCompleted(object arg) {
            if ((this._QuickSaleReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._QuickSaleReportCompleted(this, new _QuickSaleReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_SalesByProductNameChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _SalesByProductNameChart(System.DateTime DateFrom, System.DateTime DateTo) {
            object[] results = this.Invoke("_SalesByProductNameChart", new object[] {
                        DateFrom,
                        DateTo});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _SalesByProductNameChartAsync(System.DateTime DateFrom, System.DateTime DateTo) {
            this._SalesByProductNameChartAsync(DateFrom, DateTo, null);
        }
        
        /// <remarks/>
        public void _SalesByProductNameChartAsync(System.DateTime DateFrom, System.DateTime DateTo, object userState) {
            if ((this._SalesByProductNameChartOperationCompleted == null)) {
                this._SalesByProductNameChartOperationCompleted = new System.Threading.SendOrPostCallback(this.On_SalesByProductNameChartOperationCompleted);
            }
            this.InvokeAsync("_SalesByProductNameChart", new object[] {
                        DateFrom,
                        DateTo}, this._SalesByProductNameChartOperationCompleted, userState);
        }
        
        private void On_SalesByProductNameChartOperationCompleted(object arg) {
            if ((this._SalesByProductNameChartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._SalesByProductNameChartCompleted(this, new _SalesByProductNameChartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_SalesByProductQuantityChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _SalesByProductQuantityChart(System.DateTime DateFrom, System.DateTime DateTo) {
            object[] results = this.Invoke("_SalesByProductQuantityChart", new object[] {
                        DateFrom,
                        DateTo});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _SalesByProductQuantityChartAsync(System.DateTime DateFrom, System.DateTime DateTo) {
            this._SalesByProductQuantityChartAsync(DateFrom, DateTo, null);
        }
        
        /// <remarks/>
        public void _SalesByProductQuantityChartAsync(System.DateTime DateFrom, System.DateTime DateTo, object userState) {
            if ((this._SalesByProductQuantityChartOperationCompleted == null)) {
                this._SalesByProductQuantityChartOperationCompleted = new System.Threading.SendOrPostCallback(this.On_SalesByProductQuantityChartOperationCompleted);
            }
            this.InvokeAsync("_SalesByProductQuantityChart", new object[] {
                        DateFrom,
                        DateTo}, this._SalesByProductQuantityChartOperationCompleted, userState);
        }
        
        private void On_SalesByProductQuantityChartOperationCompleted(object arg) {
            if ((this._SalesByProductQuantityChartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._SalesByProductQuantityChartCompleted(this, new _SalesByProductQuantityChartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Purchase {
        
        private int idField;
        
        private string invoiceNoField;
        
        private System.DateTime purchaseDateField;
        
        private int supplierIDField;
        
        private double amountField;
        
        private double paymentField;
        
        private double balanceField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PurchaseDate {
            get {
                return this.purchaseDateField;
            }
            set {
                this.purchaseDateField = value;
            }
        }
        
        /// <remarks/>
        public int SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleDetail {
        
        private int idField;
        
        private string invoiceNoField;
        
        private int productIDField;
        
        private int quantityField;
        
        private double buyingValueField;
        
        private double sellingValueField;
        
        private double amountField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public double BuyingValue {
            get {
                return this.buyingValueField;
            }
            set {
                this.buyingValueField = value;
            }
        }
        
        /// <remarks/>
        public double SellingValue {
            get {
                return this.sellingValueField;
            }
            set {
                this.sellingValueField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sale {
        
        private int idField;
        
        private string invoiceNoField;
        
        private System.DateTime sellDateField;
        
        private int customerIDField;
        
        private double amountField;
        
        private double discountField;
        
        private double paymentField;
        
        private double balanceField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SellDate {
            get {
                return this.sellDateField;
            }
            set {
                this.sellDateField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        public double Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseDetail {
        
        private int idField;
        
        private string invoiceNoField;
        
        private int productIDField;
        
        private int quantityField;
        
        private double buyingValueField;
        
        private double sellingValueField;
        
        private double amountField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public double BuyingValue {
            get {
                return this.buyingValueField;
            }
            set {
                this.buyingValueField = value;
            }
        }
        
        /// <remarks/>
        public double SellingValue {
            get {
                return this.sellingValueField;
            }
            set {
                this.sellingValueField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServerToClient {
        
        private int countField;
        
        private double valueField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        private string messageField;
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DS {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddPurchaseCompletedEventHandler(object sender, _AddPurchaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddPurchaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddPurchaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddPurchaseDetailCompletedEventHandler(object sender, _AddPurchaseDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddPurchaseDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddPurchaseDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _ViewPurchaseByDateCompletedEventHandler(object sender, _ViewPurchaseByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _ViewPurchaseByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _ViewPurchaseByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _ViewPurchaseByDatesCompletedEventHandler(object sender, _ViewPurchaseByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _ViewPurchaseByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _ViewPurchaseByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddSaleCompletedEventHandler(object sender, _AddSaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddSaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddSaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddSaleDetailsCompletedEventHandler(object sender, _AddSaleDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddSaleDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddSaleDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSalesCompletedEventHandler(object sender, _GetSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSalesByInvoiceCompletedEventHandler(object sender, _GetSalesByInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSalesByInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSalesByInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSalesByDateCompletedEventHandler(object sender, _GetSalesByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSalesByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSalesByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSalesByDatesCompletedEventHandler(object sender, _GetSalesByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSalesByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSalesByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _QuickSaleReportCompletedEventHandler(object sender, _QuickSaleReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _QuickSaleReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _QuickSaleReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _SalesByProductNameChartCompletedEventHandler(object sender, _SalesByProductNameChartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _SalesByProductNameChartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _SalesByProductNameChartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _SalesByProductQuantityChartCompletedEventHandler(object sender, _SalesByProductQuantityChartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _SalesByProductQuantityChartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _SalesByProductQuantityChartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591