//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KVM.wrSettings {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MySettingsSoap", Namespace="http://tempuri.org/")]
    public partial class MySettings : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFinancialYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRetailInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesInvoiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MySettings() {
            this.Url = global::KVM.Properties.Settings.Default.KV_Mart_wrSettings_MySettings;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFinancialYearCompletedEventHandler GetFinancialYearCompleted;
        
        /// <remarks/>
        public event GetRetailInvoiceCompletedEventHandler GetRetailInvoiceCompleted;
        
        /// <remarks/>
        public event GetSalesInvoiceCompletedEventHandler GetSalesInvoiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFinancialYear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFinancialYear(System.DateTime dt) {
            object[] results = this.Invoke("GetFinancialYear", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFinancialYearAsync(System.DateTime dt) {
            this.GetFinancialYearAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetFinancialYearAsync(System.DateTime dt, object userState) {
            if ((this.GetFinancialYearOperationCompleted == null)) {
                this.GetFinancialYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFinancialYearOperationCompleted);
            }
            this.InvokeAsync("GetFinancialYear", new object[] {
                        dt}, this.GetFinancialYearOperationCompleted, userState);
        }
        
        private void OnGetFinancialYearOperationCompleted(object arg) {
            if ((this.GetFinancialYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFinancialYearCompleted(this, new GetFinancialYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRetailInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRetailInvoice(System.DateTime dt, string Table, string ShortName) {
            object[] results = this.Invoke("GetRetailInvoice", new object[] {
                        dt,
                        Table,
                        ShortName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRetailInvoiceAsync(System.DateTime dt, string Table, string ShortName) {
            this.GetRetailInvoiceAsync(dt, Table, ShortName, null);
        }
        
        /// <remarks/>
        public void GetRetailInvoiceAsync(System.DateTime dt, string Table, string ShortName, object userState) {
            if ((this.GetRetailInvoiceOperationCompleted == null)) {
                this.GetRetailInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRetailInvoiceOperationCompleted);
            }
            this.InvokeAsync("GetRetailInvoice", new object[] {
                        dt,
                        Table,
                        ShortName}, this.GetRetailInvoiceOperationCompleted, userState);
        }
        
        private void OnGetRetailInvoiceOperationCompleted(object arg) {
            if ((this.GetRetailInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRetailInvoiceCompleted(this, new GetRetailInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSalesInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSalesInvoice(System.DateTime dt, string ShortName) {
            object[] results = this.Invoke("GetSalesInvoice", new object[] {
                        dt,
                        ShortName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesInvoiceAsync(System.DateTime dt, string ShortName) {
            this.GetSalesInvoiceAsync(dt, ShortName, null);
        }
        
        /// <remarks/>
        public void GetSalesInvoiceAsync(System.DateTime dt, string ShortName, object userState) {
            if ((this.GetSalesInvoiceOperationCompleted == null)) {
                this.GetSalesInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesInvoiceOperationCompleted);
            }
            this.InvokeAsync("GetSalesInvoice", new object[] {
                        dt,
                        ShortName}, this.GetSalesInvoiceOperationCompleted, userState);
        }
        
        private void OnGetSalesInvoiceOperationCompleted(object arg) {
            if ((this.GetSalesInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesInvoiceCompleted(this, new GetSalesInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetFinancialYearCompletedEventHandler(object sender, GetFinancialYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFinancialYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFinancialYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetRetailInvoiceCompletedEventHandler(object sender, GetRetailInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRetailInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRetailInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSalesInvoiceCompletedEventHandler(object sender, GetSalesInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591