//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KVM.wrProducts {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductsSoap", Namespace="http://tempuri.org/")]
    public partial class Products : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSubCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetSubCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _AddCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _UpdateCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _DeleteCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetProductDetailByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetProductCountByBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetProductDataByBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback _GetProductDetailByBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback _InsertProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback _UpdateProductQuantityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Products() {
            this.Url = global::KVM.Properties.Settings.Default.KV_Mart_wrProducts_Products;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _GetCategoriesCompletedEventHandler _GetCategoriesCompleted;
        
        /// <remarks/>
        public event _GetCategoryCompletedEventHandler _GetCategoryCompleted;
        
        /// <remarks/>
        public event _GetSubCategoryCompletedEventHandler _GetSubCategoryCompleted;
        
        /// <remarks/>
        public event _GetSubCategoriesCompletedEventHandler _GetSubCategoriesCompleted;
        
        /// <remarks/>
        public event _GetCompaniesCompletedEventHandler _GetCompaniesCompleted;
        
        /// <remarks/>
        public event _AddCategoryCompletedEventHandler _AddCategoryCompleted;
        
        /// <remarks/>
        public event _UpdateCategoryCompletedEventHandler _UpdateCategoryCompleted;
        
        /// <remarks/>
        public event _DeleteCategoryCompletedEventHandler _DeleteCategoryCompleted;
        
        /// <remarks/>
        public event _GetProductsCompletedEventHandler _GetProductsCompleted;
        
        /// <remarks/>
        public event _GetProductDetailByIDCompletedEventHandler _GetProductDetailByIDCompleted;
        
        /// <remarks/>
        public event _GetProductCountByBarCodeCompletedEventHandler _GetProductCountByBarCodeCompleted;
        
        /// <remarks/>
        public event _GetProductDataByBarCodeCompletedEventHandler _GetProductDataByBarCodeCompleted;
        
        /// <remarks/>
        public event _GetProductDetailByBarCodeCompletedEventHandler _GetProductDetailByBarCodeCompleted;
        
        /// <remarks/>
        public event _InsertProductCompletedEventHandler _InsertProductCompleted;
        
        /// <remarks/>
        public event _UpdateProductQuantityCompletedEventHandler _UpdateProductQuantityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCategories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetCategories() {
            object[] results = this.Invoke("_GetCategories", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCategoriesAsync() {
            this._GetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void _GetCategoriesAsync(object userState) {
            if ((this._GetCategoriesOperationCompleted == null)) {
                this._GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCategoriesOperationCompleted);
            }
            this.InvokeAsync("_GetCategories", new object[0], this._GetCategoriesOperationCompleted, userState);
        }
        
        private void On_GetCategoriesOperationCompleted(object arg) {
            if ((this._GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCategoriesCompleted(this, new _GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category _GetCategory(int ID) {
            object[] results = this.Invoke("_GetCategory", new object[] {
                        ID});
            return ((Category)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCategoryAsync(int ID) {
            this._GetCategoryAsync(ID, null);
        }
        
        /// <remarks/>
        public void _GetCategoryAsync(int ID, object userState) {
            if ((this._GetCategoryOperationCompleted == null)) {
                this._GetCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCategoryOperationCompleted);
            }
            this.InvokeAsync("_GetCategory", new object[] {
                        ID}, this._GetCategoryOperationCompleted, userState);
        }
        
        private void On_GetCategoryOperationCompleted(object arg) {
            if ((this._GetCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCategoryCompleted(this, new _GetCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSubCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSubCategory(int CategoryID) {
            object[] results = this.Invoke("_GetSubCategory", new object[] {
                        CategoryID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSubCategoryAsync(int CategoryID) {
            this._GetSubCategoryAsync(CategoryID, null);
        }
        
        /// <remarks/>
        public void _GetSubCategoryAsync(int CategoryID, object userState) {
            if ((this._GetSubCategoryOperationCompleted == null)) {
                this._GetSubCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSubCategoryOperationCompleted);
            }
            this.InvokeAsync("_GetSubCategory", new object[] {
                        CategoryID}, this._GetSubCategoryOperationCompleted, userState);
        }
        
        private void On_GetSubCategoryOperationCompleted(object arg) {
            if ((this._GetSubCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSubCategoryCompleted(this, new _GetSubCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetSubCategories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetSubCategories() {
            object[] results = this.Invoke("_GetSubCategories", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetSubCategoriesAsync() {
            this._GetSubCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void _GetSubCategoriesAsync(object userState) {
            if ((this._GetSubCategoriesOperationCompleted == null)) {
                this._GetSubCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetSubCategoriesOperationCompleted);
            }
            this.InvokeAsync("_GetSubCategories", new object[0], this._GetSubCategoriesOperationCompleted, userState);
        }
        
        private void On_GetSubCategoriesOperationCompleted(object arg) {
            if ((this._GetSubCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetSubCategoriesCompleted(this, new _GetSubCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetCompanies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetCompanies() {
            object[] results = this.Invoke("_GetCompanies", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetCompaniesAsync() {
            this._GetCompaniesAsync(null);
        }
        
        /// <remarks/>
        public void _GetCompaniesAsync(object userState) {
            if ((this._GetCompaniesOperationCompleted == null)) {
                this._GetCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetCompaniesOperationCompleted);
            }
            this.InvokeAsync("_GetCompanies", new object[0], this._GetCompaniesOperationCompleted, userState);
        }
        
        private void On_GetCompaniesOperationCompleted(object arg) {
            if ((this._GetCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetCompaniesCompleted(this, new _GetCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_AddCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _AddCategory(Category c) {
            object[] results = this.Invoke("_AddCategory", new object[] {
                        c});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _AddCategoryAsync(Category c) {
            this._AddCategoryAsync(c, null);
        }
        
        /// <remarks/>
        public void _AddCategoryAsync(Category c, object userState) {
            if ((this._AddCategoryOperationCompleted == null)) {
                this._AddCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_AddCategoryOperationCompleted);
            }
            this.InvokeAsync("_AddCategory", new object[] {
                        c}, this._AddCategoryOperationCompleted, userState);
        }
        
        private void On_AddCategoryOperationCompleted(object arg) {
            if ((this._AddCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._AddCategoryCompleted(this, new _AddCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_UpdateCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _UpdateCategory(Category c) {
            object[] results = this.Invoke("_UpdateCategory", new object[] {
                        c});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _UpdateCategoryAsync(Category c) {
            this._UpdateCategoryAsync(c, null);
        }
        
        /// <remarks/>
        public void _UpdateCategoryAsync(Category c, object userState) {
            if ((this._UpdateCategoryOperationCompleted == null)) {
                this._UpdateCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_UpdateCategoryOperationCompleted);
            }
            this.InvokeAsync("_UpdateCategory", new object[] {
                        c}, this._UpdateCategoryOperationCompleted, userState);
        }
        
        private void On_UpdateCategoryOperationCompleted(object arg) {
            if ((this._UpdateCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._UpdateCategoryCompleted(this, new _UpdateCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_DeleteCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _DeleteCategory(int ID) {
            object[] results = this.Invoke("_DeleteCategory", new object[] {
                        ID});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _DeleteCategoryAsync(int ID) {
            this._DeleteCategoryAsync(ID, null);
        }
        
        /// <remarks/>
        public void _DeleteCategoryAsync(int ID, object userState) {
            if ((this._DeleteCategoryOperationCompleted == null)) {
                this._DeleteCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_DeleteCategoryOperationCompleted);
            }
            this.InvokeAsync("_DeleteCategory", new object[] {
                        ID}, this._DeleteCategoryOperationCompleted, userState);
        }
        
        private void On_DeleteCategoryOperationCompleted(object arg) {
            if ((this._DeleteCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._DeleteCategoryCompleted(this, new _DeleteCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetProducts() {
            object[] results = this.Invoke("_GetProducts", new object[0]);
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetProductsAsync() {
            this._GetProductsAsync(null);
        }
        
        /// <remarks/>
        public void _GetProductsAsync(object userState) {
            if ((this._GetProductsOperationCompleted == null)) {
                this._GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetProductsOperationCompleted);
            }
            this.InvokeAsync("_GetProducts", new object[0], this._GetProductsOperationCompleted, userState);
        }
        
        private void On_GetProductsOperationCompleted(object arg) {
            if ((this._GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetProductsCompleted(this, new _GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetProductDetailByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product _GetProductDetailByID(int ID) {
            object[] results = this.Invoke("_GetProductDetailByID", new object[] {
                        ID});
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void _GetProductDetailByIDAsync(int ID) {
            this._GetProductDetailByIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void _GetProductDetailByIDAsync(int ID, object userState) {
            if ((this._GetProductDetailByIDOperationCompleted == null)) {
                this._GetProductDetailByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetProductDetailByIDOperationCompleted);
            }
            this.InvokeAsync("_GetProductDetailByID", new object[] {
                        ID}, this._GetProductDetailByIDOperationCompleted, userState);
        }
        
        private void On_GetProductDetailByIDOperationCompleted(object arg) {
            if ((this._GetProductDetailByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetProductDetailByIDCompleted(this, new _GetProductDetailByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetProductCountByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int _GetProductCountByBarCode(string BarCode) {
            object[] results = this.Invoke("_GetProductCountByBarCode", new object[] {
                        BarCode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void _GetProductCountByBarCodeAsync(string BarCode) {
            this._GetProductCountByBarCodeAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void _GetProductCountByBarCodeAsync(string BarCode, object userState) {
            if ((this._GetProductCountByBarCodeOperationCompleted == null)) {
                this._GetProductCountByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetProductCountByBarCodeOperationCompleted);
            }
            this.InvokeAsync("_GetProductCountByBarCode", new object[] {
                        BarCode}, this._GetProductCountByBarCodeOperationCompleted, userState);
        }
        
        private void On_GetProductCountByBarCodeOperationCompleted(object arg) {
            if ((this._GetProductCountByBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetProductCountByBarCodeCompleted(this, new _GetProductCountByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetProductDataByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _GetProductDataByBarCode(string BarCode) {
            object[] results = this.Invoke("_GetProductDataByBarCode", new object[] {
                        BarCode});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _GetProductDataByBarCodeAsync(string BarCode) {
            this._GetProductDataByBarCodeAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void _GetProductDataByBarCodeAsync(string BarCode, object userState) {
            if ((this._GetProductDataByBarCodeOperationCompleted == null)) {
                this._GetProductDataByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetProductDataByBarCodeOperationCompleted);
            }
            this.InvokeAsync("_GetProductDataByBarCode", new object[] {
                        BarCode}, this._GetProductDataByBarCodeOperationCompleted, userState);
        }
        
        private void On_GetProductDataByBarCodeOperationCompleted(object arg) {
            if ((this._GetProductDataByBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetProductDataByBarCodeCompleted(this, new _GetProductDataByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_GetProductDetailByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product _GetProductDetailByBarCode(string BarCode) {
            object[] results = this.Invoke("_GetProductDetailByBarCode", new object[] {
                        BarCode});
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void _GetProductDetailByBarCodeAsync(string BarCode) {
            this._GetProductDetailByBarCodeAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void _GetProductDetailByBarCodeAsync(string BarCode, object userState) {
            if ((this._GetProductDetailByBarCodeOperationCompleted == null)) {
                this._GetProductDetailByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.On_GetProductDetailByBarCodeOperationCompleted);
            }
            this.InvokeAsync("_GetProductDetailByBarCode", new object[] {
                        BarCode}, this._GetProductDetailByBarCodeOperationCompleted, userState);
        }
        
        private void On_GetProductDetailByBarCodeOperationCompleted(object arg) {
            if ((this._GetProductDetailByBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._GetProductDetailByBarCodeCompleted(this, new _GetProductDetailByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_InsertProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _InsertProduct(Product p) {
            object[] results = this.Invoke("_InsertProduct", new object[] {
                        p});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _InsertProductAsync(Product p) {
            this._InsertProductAsync(p, null);
        }
        
        /// <remarks/>
        public void _InsertProductAsync(Product p, object userState) {
            if ((this._InsertProductOperationCompleted == null)) {
                this._InsertProductOperationCompleted = new System.Threading.SendOrPostCallback(this.On_InsertProductOperationCompleted);
            }
            this.InvokeAsync("_InsertProduct", new object[] {
                        p}, this._InsertProductOperationCompleted, userState);
        }
        
        private void On_InsertProductOperationCompleted(object arg) {
            if ((this._InsertProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._InsertProductCompleted(this, new _InsertProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_UpdateProductQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServerToClient _UpdateProductQuantity(int qty, string mode, int pid) {
            object[] results = this.Invoke("_UpdateProductQuantity", new object[] {
                        qty,
                        mode,
                        pid});
            return ((ServerToClient)(results[0]));
        }
        
        /// <remarks/>
        public void _UpdateProductQuantityAsync(int qty, string mode, int pid) {
            this._UpdateProductQuantityAsync(qty, mode, pid, null);
        }
        
        /// <remarks/>
        public void _UpdateProductQuantityAsync(int qty, string mode, int pid, object userState) {
            if ((this._UpdateProductQuantityOperationCompleted == null)) {
                this._UpdateProductQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.On_UpdateProductQuantityOperationCompleted);
            }
            this.InvokeAsync("_UpdateProductQuantity", new object[] {
                        qty,
                        mode,
                        pid}, this._UpdateProductQuantityOperationCompleted, userState);
        }
        
        private void On_UpdateProductQuantityOperationCompleted(object arg) {
            if ((this._UpdateProductQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._UpdateProductQuantityCompleted(this, new _UpdateProductQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServerToClient {
        
        private int countField;
        
        private double valueField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        private string messageField;
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DS {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Product {
        
        private int idField;
        
        private int categoryField;
        
        private string subCategoryField;
        
        private string companyField;
        
        private string productNameField;
        
        private string packageSizeField;
        
        private double buyingValueField;
        
        private double sellingValueField;
        
        private string mfgDateField;
        
        private string expDateField;
        
        private int quantityField;
        
        private string barCodeField;
        
        private string hSNField;
        
        private double taxRateField;
        
        private int supplierIDField;
        
        private int countField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string SubCategory {
            get {
                return this.subCategoryField;
            }
            set {
                this.subCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string PackageSize {
            get {
                return this.packageSizeField;
            }
            set {
                this.packageSizeField = value;
            }
        }
        
        /// <remarks/>
        public double BuyingValue {
            get {
                return this.buyingValueField;
            }
            set {
                this.buyingValueField = value;
            }
        }
        
        /// <remarks/>
        public double SellingValue {
            get {
                return this.sellingValueField;
            }
            set {
                this.sellingValueField = value;
            }
        }
        
        /// <remarks/>
        public string MfgDate {
            get {
                return this.mfgDateField;
            }
            set {
                this.mfgDateField = value;
            }
        }
        
        /// <remarks/>
        public string ExpDate {
            get {
                return this.expDateField;
            }
            set {
                this.expDateField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HSN {
            get {
                return this.hSNField;
            }
            set {
                this.hSNField = value;
            }
        }
        
        /// <remarks/>
        public double TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        public int SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Category {
        
        private int idField;
        
        private string categoryNameField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCategoriesCompletedEventHandler(object sender, _GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCategoryCompletedEventHandler(object sender, _GetCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSubCategoryCompletedEventHandler(object sender, _GetSubCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSubCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSubCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetSubCategoriesCompletedEventHandler(object sender, _GetSubCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetSubCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetSubCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetCompaniesCompletedEventHandler(object sender, _GetCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _AddCategoryCompletedEventHandler(object sender, _AddCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _AddCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _AddCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _UpdateCategoryCompletedEventHandler(object sender, _UpdateCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _UpdateCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _UpdateCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _DeleteCategoryCompletedEventHandler(object sender, _DeleteCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _DeleteCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _DeleteCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetProductsCompletedEventHandler(object sender, _GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetProductDetailByIDCompletedEventHandler(object sender, _GetProductDetailByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetProductDetailByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetProductDetailByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetProductCountByBarCodeCompletedEventHandler(object sender, _GetProductCountByBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetProductCountByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetProductCountByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetProductDataByBarCodeCompletedEventHandler(object sender, _GetProductDataByBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetProductDataByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetProductDataByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _GetProductDetailByBarCodeCompletedEventHandler(object sender, _GetProductDetailByBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _GetProductDetailByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _GetProductDetailByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _InsertProductCompletedEventHandler(object sender, _InsertProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _InsertProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _InsertProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void _UpdateProductQuantityCompletedEventHandler(object sender, _UpdateProductQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _UpdateProductQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _UpdateProductQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServerToClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerToClient)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591